name: Testing a REST API with Cypress
on: 
  push:
    branches: [ ci ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Project checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' 
        with:
          node-version: 14.x
      - name: installation of dependencies
        run: npm ci
      - name: API Automated Tests
        run: npm run cypress:open && cypress:run