name: API Tests - Cypress

on: 
  push:
      branches: [ master, main, develop]
  pull_request:
      branches: [ master, main, develop]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:        
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - run: |
            npm run back2thePast
      - name: Run Cypress Tests 🧪        
        uses: cypress-io/github-action@v4.1.0      
        with:
          wait-on: ${{ secrets.BASE_URL_API }}
          wait-on-timeout: 60          
          browser: chrome
          record: false
          headed: true
          group: 'API-Tests-Cypress'
          spec: cypress/integration/*.spec.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
